### ISSUE TITLE
Cross platform integration

### ISSUE THREAD

**Issue by AfromD** [kubilus1/autoortho#1]
Hi,
Thanks for developing this. I found a fusepy fork that concentrates on cross platform integration with winfsp and fuse for macos. Maybe this is helpful in supporting MacOS and Windows. AFAIK, you just need to adjust your imported functions.
https://github.com/cdrini/refuse/tree/cdrini-patch-1
(most appropriate fork I think). As it is Alpha (but high level functions seem to be tested) maybe you want to keep using standard fusepy for linux.
I can test on windows

**Comment by kubilus1** [comment]
I've actually been testing out cross platform support on a Windows 10 VM this past week.  I'm pretty confident that with WinFSP and a few tweaks I'm currently working on that this should work even with the standard fusepy.  At least enough to take to the next level of experimental testing.

**Comment by ivotaHR** [comment]
Hi. I installed winfsp-1.10.22006.msi , but how configure it? any tutorial? thank you

**Comment by kubilus1** [comment]
You should just have to download the latest WinFSP release and it install it normally: https://github.com/winfsp/winfsp/releases

**Comment by kubilus1** [comment]
As far as usage, WinFSP should just automatically handle the FUSE setup from the program.  Usage should be: https://github.com/kubilus1/autoortho#experimental-windows-setup

**Comment by ivotaHR** [comment]
I installed WINFSP  2022 with Core and Developer features.
I will try. I will report here. Thank you

**Comment by ivotaHR** [comment]
[https://ibb.co/TbQfdp2](url)

- installed WINFSP (restarted PC)
- python3 -m pip install -U -r requirements.txt
- make empty TEST folder  (C:\autoortho\TEST) , make empty folder ORTHO\Earth nav data\  (C:\X-Plane 11\Custom Scenery\ORTHO) then put path in scenery_packs.ini on the  EOF.
- run python.exe  autoortho .\TEST C:\X-Plane 11\Custom Scenery\ORTHO

Program started, but look mounitpoint -> C:\X-Plane ( have to be C:\X-Plane 11\Custom Scenery\ORTHO)

Thank you

**Comment by doxbot-gh-actions** [comment]
Looks like it's running, good!  

The 'TEST' folder should still be a directory structure as created by Ortho4XP:  https://github.com/kubilus1/autoortho#usage  and https://github.com/kubilus1/autoortho#ortho4xp-usage-tips

It would be cool eventually I think to package up some of these 'dds-free' orthophotos, but for now you need to supply your own.

If you want to do a quick test though, if you create an empty/0 byte file under your TEST directory of the right format.  For instance `24832_12416_BI16.dds` you should see it show up as a satellite image under your mounted dir:  C:\X-Plane 11\Custom Scenery\ORTHO

You can see under the project I have some test 0 byte files:  https://github.com/kubilus1/autoortho/tree/main/autoortho/testfiles

**Comment by kubilus1** [comment]
Looks like it's running, good!

The 'TEST' folder should still be a directory structure as created by Ortho4XP: https://github.com/kubilus1/autoortho#usage and https://github.com/kubilus1/autoortho#ortho4xp-usage-tips

It would be cool eventually I think to package up some of these 'dds-free' orthophotos, but for now you need to supply your own.

If you want to do a quick test though, if you create an empty/0 byte file under your TEST directory of the right format. For instance 24832_12416_BI16.dds you should see it show up as a satellite image under your mounted dir: C:\X-Plane 11\Custom Scenery\ORTHO

You can see under the project I have some test 0 byte files: https://github.com/kubilus1/autoortho/tree/main/autoortho/testfiles

**Comment by ivotaHR** [comment]
It seems problem to PATH?

attempts:
1. python.exe .\autoortho.py .\TEST C:\X-Plane 11\Custom Scenery\ORTHO
2. python.exe .\autoortho.py .\TEST C:\X-Plane%11\Custom Scenery\ORTHO
3. python.exe .\autoortho.py .\TEST C:\X-Plane%11\Custom%Scenery\ORTHO
4. python.exe .\autoortho.py '.\TEST' 'C:\X-Plane 11\Custom Scenery\ORTHO'
5. python.exe .\autoortho.py '.\TEST\' 'C:\X-Plane 11\Custom Scenery\ORTHO\'
6. python.exe .\autoortho.py ".\TEST\" "C:\X-Plane 11\Custom Scenery\ORTHO\"

Only first attempt works. But mount point is wrong : shoud be C:\X-Plane 11\Custom Scenery\ORTHO\ not  C:\X-Plane

Missing  X-PLANE 11 (maybe space made problem, or  poor windows OS)

here is log:

PS C:\autoortho> C:\Users\Ivica\AppData\Local\Programs\Python\Python310\python.exe .\autoortho.py .\TEST C:\X-Plane 11\Custom Scenery\ORTHO
Windows detected
INFO:log:chunk_getter: <getortho.ChunkGetter object at 0x0000027879DE8C70>
INFO:log:tile_getter: <getortho.TileGetter object at 0x000002787A01DA80>
INFO:log:AutoOrtho:  root: .\TEST  mountpoint: C:\X-Plane
INFO:log:ROOT: .\TEST
INFO:log:Started tile clean thread.  Mem limit 2147483648
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
The service python has been started.
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:GETATTR: Fetch for /24832_12416_BI16.dds: ('24832', '12416', 'BI', '16')
INFO:log:GETATTR: Fetch for /24832_12416_BI16.dds: ('24832', '12416', 'BI', '16')
INFO:log:GETATTR: Fetch for /24832_12416_BI16.dds: ('24832', '12416', 'BI', '16')
INFO:log:OPEN: /24832_12416_BI16.dds, 0
INFO:log:OPEN: FULL PATH: .\TEST\24832_12416_BI16.dds
INFO:log:FH: 0
INFO:log:RELEASE: /24832_12416_BI16.dds
INFO:log:GETATTR: Fetch for /24832_12416_BI16.dds: ('24832', '12416', 'BI', '16')
INFO:log:RELEASE: /24832_12416_BI16.dds
INFO:log:GETATTR: Fetch for /24832_12416_BI16.dds: ('24832', '12416', 'BI', '16')
INFO:log:OPEN: /24832_12416_BI16.dds, 0
INFO:log:OPEN: FULL PATH: .\TEST\24832_12416_BI16.dds
INFO:log:FH: 0
INFO:log:RELEASE: /24832_12416_BI16.dds
INFO:log:GETATTR: Fetch for /24832_12416_BI16.dds: ('24832', '12416', 'BI', '16')
INFO:log:RELEASE: /24832_12416_BI16.dds
INFO:log:GETATTR: Fetch for /24832_12416_BI16.dds: ('24832', '12416', 'BI', '16')
INFO:log:OPEN: /24832_12416_BI16.dds, 0
INFO:log:OPEN: FULL PATH: .\TEST\24832_12416_BI16.dds
INFO:log:FH: 0
INFO:log:RELEASE: /24832_12416_BI16.dds
INFO:log:GETATTR: Fetch for /24832_12416_BI16.dds: ('24832', '12416', 'BI', '16')
INFO:log:RELEASE: /24832_12416_BI16.dds
INFO:log:GETATTR: Fetch for /24832_12416_BI16.dds: ('24832', '12416', 'BI', '16')
INFO:log:OPEN: /24832_12416_BI16.dds, 0
INFO:log:OPEN: FULL PATH: .\TEST\24832_12416_BI16.dds
INFO:log:FH: 0
INFO:log:RELEASE: /24832_12416_BI16.dds
INFO:log:RELEASE: /24832_12416_BI16.dds
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 23 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 23 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 23 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 23 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 23 MB
The service python has been stopped.
PS C:\autoortho> C:\Users\Ivica\AppData\Local\Programs\Python\Python310\python.exe .\autoortho.py .\TEST C:\X-Plane%11\Custom Scenery\ORTHO
Windows detected
INFO:log:chunk_getter: <getortho.ChunkGetter object at 0x000001A1ACEA8C40>
INFO:log:tile_getter: <getortho.TileGetter object at 0x000001A1AD10DA50>
INFO:log:AutoOrtho:  root: .\TEST  mountpoint: C:\X-Plane%11\Custom
INFO:log:ROOT: .\TEST
INFO:log:Started tile clean thread.  Mem limit 2147483648
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
Cannot create WinFsp-FUSE file system: invalid mount point.
Traceback (most recent call last):
  File "C:\autoortho\autoortho.py", line 338, in <module>
    main(sys.argv[2], sys.argv[1])
  File "C:\autoortho\autoortho.py", line 334, in main
    FUSE(AutoOrtho(root), mountpoint, nothreads=nothreads, foreground=True, allow_other=True)
  File "C:\Users\Ivica\AppData\Local\Programs\Python\Python310\lib\site-packages\fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1
PS C:\autoortho> C:\Users\Ivica\AppData\Local\Programs\Python\Python310\python.exe .\autoortho.py .\TEST C:\X-Plane%11\Custom%Scenery\ORTHO
Windows detected
INFO:log:chunk_getter: <getortho.ChunkGetter object at 0x000002380A028C10>
INFO:log:tile_getter: <getortho.TileGetter object at 0x000002380A68DA20>
INFO:log:AutoOrtho:  root: .\TEST  mountpoint: C:\X-Plane%11\Custom%Scenery\ORTHO
INFO:log:ROOT: .\TEST
INFO:log:Started tile clean thread.  Mem limit 2147483648
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 21 MB
Cannot create WinFsp-FUSE file system: invalid mount point.
Traceback (most recent call last):
  File "C:\autoortho\autoortho.py", line 338, in <module>
    main(sys.argv[2], sys.argv[1])
  File "C:\autoortho\autoortho.py", line 334, in main
    FUSE(AutoOrtho(root), mountpoint, nothreads=nothreads, foreground=True, allow_other=True)
  File "C:\Users\Ivica\AppData\Local\Programs\Python\Python310\lib\site-packages\fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1
PS C:\autoortho> C:\Users\Ivica\AppData\Local\Programs\Python\Python310\python.exe .\autoortho.py '.\TEST' 'C:\X-Plane 11\Custom Scenery\ORTHO'
Windows detected
INFO:log:chunk_getter: <getortho.ChunkGetter object at 0x0000023398028C10>
INFO:log:tile_getter: <getortho.TileGetter object at 0x000002339863DA20>
INFO:log:AutoOrtho:  root: .\TEST  mountpoint: C:\X-Plane 11\Custom Scenery\ORTHO
INFO:log:ROOT: .\TEST
INFO:log:Started tile clean thread.  Mem limit 2147483648
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
Cannot create WinFsp-FUSE file system: mount point in use.
Traceback (most recent call last):
  File "C:\autoortho\autoortho.py", line 338, in <module>
    main(sys.argv[2], sys.argv[1])
  File "C:\autoortho\autoortho.py", line 334, in main
    FUSE(AutoOrtho(root), mountpoint, nothreads=nothreads, foreground=True, allow_other=True)
  File "C:\Users\Ivica\AppData\Local\Programs\Python\Python310\lib\site-packages\fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1
PS C:\autoortho> C:\Users\Ivica\AppData\Local\Programs\Python\Python310\python.exe .\autoortho.py '.\TEST\' 'C:\X-Plane 11\Custom Scenery\ORTHO\'
Windows detected
INFO:log:chunk_getter: <getortho.ChunkGetter object at 0x000001D4492B8C10>
INFO:log:tile_getter: <getortho.TileGetter object at 0x000001D4494CDA20>
INFO:log:AutoOrtho:  root: .\TEST\  mountpoint: C:\X-Plane 11\Custom Scenery\ORTHO"
INFO:log:ROOT: .\TEST\
INFO:log:Started tile clean thread.  Mem limit 2147483648
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
Cannot create WinFsp-FUSE file system: invalid mount point.
Traceback (most recent call last):
  File "C:\autoortho\autoortho.py", line 338, in <module>
    main(sys.argv[2], sys.argv[1])
  File "C:\autoortho\autoortho.py", line 334, in main
    FUSE(AutoOrtho(root), mountpoint, nothreads=nothreads, foreground=True, allow_other=True)
  File "C:\Users\Ivica\AppData\Local\Programs\Python\Python310\lib\site-packages\fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1
PS C:\autoortho> C:\Users\Ivica\AppData\Local\Programs\Python\Python310\python.exe .\autoortho.py ".\TEST\" "C:\X-Plane 11\Custom Scenery\ORTHO\"
Windows detected
INFO:log:chunk_getter: <getortho.ChunkGetter object at 0x0000021770C58C10>
INFO:log:tile_getter: <getortho.TileGetter object at 0x0000021770EBDA20>
INFO:log:AutoOrtho:  root: .\TEST\  mountpoint: C:\X-Plane 11\Custom Scenery\ORTHO"
INFO:log:ROOT: .\TEST\
INFO:log:Started tile clean thread.  Mem limit 2147483648
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
Cannot create WinFsp-FUSE file system: invalid mount point.
Traceback (most recent call last):
  File "C:\autoortho\autoortho.py", line 338, in <module>
    main(sys.argv[2], sys.argv[1])
  File "C:\autoortho\autoortho.py", line 334, in main
    FUSE(AutoOrtho(root), mountpoint, nothreads=nothreads, foreground=True, allow_other=True)
  File "C:\Users\Ivica\AppData\Local\Programs\Python\Python310\lib\site-packages\fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1
PS C:\autoortho>

**Comment by kubilus1** [comment]
Thanks for the feedback, I'll take a look.

**Comment by kubilus1** [comment]
Can you verify if the directory C:\X-Plane 11\Custom Scenery\ORTHO already exists or not?  For WinFSP to work the folder cannot already exist.

**Comment by ivotaHR** [comment]
Aha, I need remove C:\X-Plane 11\Custom Scenery\ORTHO
WinFSP will make it!! Now Is clear. I still now know program works ( DSF files???), but enough for today, sse ya. Thx

Now works, here is log:

PS C:\autoortho> C:\Users\Ivica\AppData\Local\Programs\Python\Python310\python.exe .\autoortho.py "TEST" "C:\X-Plane 11\Custom Scenery\ORTHO"
Windows detected
INFO:log:chunk_getter: <getortho.ChunkGetter object at 0x00000269DDF28C10>
INFO:log:tile_getter: <getortho.TileGetter object at 0x00000269DE18DA20>
INFO:log:AutoOrtho:  root: TEST  mountpoint: C:\X-Plane 11\Custom Scenery\ORTHO
INFO:log:ROOT: TEST
INFO:log:Started tile clean thread.  Mem limit 2147483648
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
The service python has been started.
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:OPEN: /Earth nav data/+30+010/+32+013.dsf, 0
INFO:log:OPEN: FULL PATH: TEST\Earth nav data/+30+010/+32+013.dsf
INFO:log:FH: 3
INFO:log:RELEASE: /Earth nav data/+30+010/+32+013.dsf
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB

**Comment by kubilus1** [comment]
Okay I've adjusted the setup a bit to now have a config file and setup prompt on initial run.  Plus a 'run.bat' file to kick this off without having to open a command prompt, if that's what you choose.

**Comment by migare** [comment]
Hello, I can't get it to work, I have followed the installation and OrthoXP instructions, when xplane loads the DSF scenery, xplane crashes, I am on windows 10, Thank you very much.

**Comment by kubilus1** [comment]
@migare  It's possible that Xplane just won't like WinFSP filesystems.  I've updated the project to dump the logs to 'autoortho.log'  You could try sending the logs (or a relevant snippet) to better see what's going on.

**Comment by migare** [comment]
Requirement already satisfied: fusepy in c:\users\****\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: pillow>=8.3.0 in c:\users\****\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (9.1.0)
Requirement already satisfied: psutil in c:\users\****\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (5.9.0)
Windows detected
INFO:log:chunk_getter: <getortho.ChunkGetter object at 0x000001C988E68040>
INFO:log:tile_getter: <getortho.TileGetter object at 0x000001C98902E590>
INFO:log:Config file found C:\Users\****\.autoortho reading...
INFO:log:AutoOrtho:  root: E:\SIMULADORES VUELO\Utils\ORTHOXP  mountpoint: E:\SIMULADORES VUELO\X-Plane 11\Custom Scenery\ORTHOFILE
INFO:log:ROOT: E:\SIMULADORES VUELO\Utils\ORTHOXP
INFO:log:Started tile clean thread.  Mem limit 2147483648
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 22 MB
The service python has been started.
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 23 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 23 MB
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 23 MB
INFO:log:OPEN: /Earth nav data/+40+000/+41+002.dsf, 0
INFO:log:OPEN: FULL PATH: E:\SIMULADORES VUELO\Utils\ORTHOXP\Earth nav data/+40+000/+41+002.dsf
INFO:log:FH: 3

Everything is here, after the last line xplane crashes, thanks

**Comment by kubilus1** [comment]
Ahh,okay it's crashing when it's trying to load the DSF file.  I have an idea what might be going on here.  I don't have a lot of time to make too many changes right now, but this points me in the right direction.  Thanks!

**Comment by kubilus1** [comment]
Quick update.  Over the last couple weeks I put together a windows 10 laptop to see if I could setup a better test env than the VM I was using.  Where I'm stuck now is that X-Plane 11 just seems to flat out refuse to 'see' the FUSE/WinFSP mounted directories.

I've also tried just seeing if I could get a vanilla FUSE pass through FS to show up, and even that wasn't working.  I suspect there is some kind of permission issue or some other secret windowsy thing.

What's funny is that other programs have no such trouble.

**Comment by SriharshaKavuri** [comment]
Windows user here. The program runs okay and mounts to the mount point folder I created under Custom Scenery. I also made sure to add it to the end of the .ini file. XP seems to ignore this folder since it contains nested folders within. I believe this issue can be alleviated if the mount point folder is set outside of the XP directory and a shortcut is placed within the Custom Scenery folder for each tile that is required to be accessed kinda like SAM is set up. I will try this out and report back my findings.

**Comment by kubilus1** [comment]
Thanks for testing.  Can you share how it crashes/log lines?

**Comment by betampona** [comment]
The project with windows is blocked?

**Comment by kubilus1** [comment]
Yeah at this point, the issue appears to be with how X-plane deals with virtual filesystems such as what WinFSP/FUSE provides.  I would have to write a whole new layered filesystem specifically for Windows that may-or-may-not end up being acceptable for X-plane.  Not impossible, but a lot of extra work for something that I would personally **never ever** use since I am not a Windows user.

Plus Xplane 12 is around the corner, and could work entirely differently in this regard, so I think I would like to see how things play out on that front.

The code for autoortho is written in such a way that if ultimately I needed to not use a FUSE based layer for a specific OS but use "Something Else (tm)" it should be technically doable.

**Comment by block62** [comment]
has someone managed to run this in Windows? I crashed too, also wondering if it works with XP12

**Comment by kubilus1** [comment]
Little update.  I've been experimenting a bit more running this on Windows and have had luck with the following approach:
* Setup WSL2 (must by wsl2, a wsl1 distro will not work) - I'm using Ubuntu 22.04 for testing.
* Install fuse and python pip:  `apt update && apt install -y python3-pip fuse`
* Download autoortho and any ortho packages (like the example utah.tgz) *inside* the WSL directory.
* Create an empty mount point within your WSL dir `mkdir ~/z_autoortho`
* Run autoortho from within WSL with both the source and mount point setup within WSL.
* From the windows side, find your 'z_autorotho' dir and create a link.  Put that link within your X-Plane Custom Scenery dir.
* Run X-Plane

I'm running this test on pretty low-spec hardware so the perf isn't great.  I can't really do an apples to apples comparison if that is down to the laptop I'm using or if WSL introduces some inefficiencies.  

BUT this does seem to work!

**Comment by SriharshaKavuri** [comment]
I gave this a try but WSL seems to have some sort of issue with fuse. 
`INFO:log:AutoOrtho:  root: ~/test  mountpoint: ~/ortho
INFO:log:ROOT: ~/test
INFO:log:Started tile clean thread.  Mem limit 2147483648
fuse: device not found, try 'modprobe fuse' first
INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 18 MB
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/hagrid/autoortho/autoortho/__main__.py", line 18, in <module>
    autoortho.main()
  File "/home/hagrid/autoortho/autoortho/autoortho.py", line 403, in main
    FUSE(AutoOrtho(root), mountpoint, nothreads=nothreads, foreground=True, allow_other=True)
  File "/usr/local/lib/python3.10/dist-packages/fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1`

I tried running `modprobe fuse` and it gives me this error - `modprobe: FATAL: Module fuse not found in directory /lib/modules/4.4.0-19041-Microsoft` 

I tried running through all the steps as mentioned both as root and a different user but it seems to obtain the same outcome both ways. Is there any specific method through which WSL is to be installed? I got mine directly from the Microsoft Store.

**Comment by kubilus1** [comment]
Yeah you are probably using WSL1 for that distro.  https://www.configserverfirewall.com/windows-10/convert-wsl-1-linux-distribution-to-wsl-2/

WSL1 cannot do FUSE, but WSL2 can.

That does fully seem to work for me, but I still think there is some slight weirdness with this setup.  For instance much more data seems to be pulled in this way leading to very long initial start times and more memory usage.  It appears that the full tile size is being pulled in, but I'll need to experiment more to isolate when I have time.

**Comment by SriharshaKavuri** [comment]
Ah that seems to have fixed it! I had to change some permissions in the fuse config file after upgrading to WSL2 
and it seems to be working without hiccups now.

**Comment by kubilus1** [comment]
NICE!  How long about did it take to initially load a flight?

**Comment by SriharshaKavuri** [comment]
I am not sure about XP11 yet but as per my testing in XP12, it seemed to perform pretty similarly to when I didn't have it installed. I have not been able to test it within the sim, however. The DSFs are not being picked up by the program for some reason

>  Linux detected
> INFO:log:chunk_getter: <getortho.ChunkGetter object at 0x7f863e55ec50>
> INFO:log:tile_getter: <getortho.TileGetter object at 0x7f863ddb56c0>
> INFO:log:Config file found /home/hagrid/.autoortho reading...
> INFO:log:AutoOrtho:  root: ~/test  mountpoint: ~/ortho
> INFO:log:ROOT: ~/test
> INFO:log:Started tile clean thread.  Mem limit 2147483648
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB
> INFO:log:NUM TILES CACHED: 0.  TOTAL MEM: 36 MB

![image](https://user-images.githubusercontent.com/19206302/192104856-49652d76-f288-49d4-ac2c-06485b39b136.png)

This is how I have the DSFs configured.

**Comment by SriharshaKavuri** [comment]
I have managed to fix the error by making the directories at the same level as the autoortho folder within the cloned git directory. Making a directory in the user folder i.e. ~/ doesn't seem to work.

**Comment by betampona** [comment]
Hi SriharshaKavuri, Did you manage to run autoortho with WSL2, if so how does the CPU and GPU perform?
Greetings

**Comment by SriharshaKavuri** [comment]
In my testing so far, CPU and GPU usage has been negligible. RAM is the biggest hurdle but it seems to put everything on the page file anyway so that's not a big deal. The visual quality is as good as you want it to be. ZL19 takes forever to download though so I'd recommend going 17 except for around airports. 
![image](https://user-images.githubusercontent.com/19206302/192766186-e99b1e2a-6a26-4c05-aa32-6db7eaedd87e.png)
 The dry-looking ring around the airport is a part of the scenery. The rest of it is autogenerated.

**Comment by betampona** [comment]
Thanks for the answer, you created an exclusion around the airport, is it native X-plane scenery and the rest is orthophotos?
That seems interesting, it only remains for Kubilus1 or you to make us a relatively detailed tuto for the implementation of Autoortho in a Windows universe.
Greetings.

**Comment by SriharshaKavuri** [comment]
> Thanks for the answer, you created an exclusion around the airport, is it native X-plane scenery and the rest is orthophotos? That seems interesting, it only remains for Kubilus1 or you to make us a relatively detailed tuto for the implementation of Autoortho in a Windows universe. Greetings.

The airport is actually a project that I worked on with a friend. I am not entirely sure how the ortho and exclusion zones intertwine, however. I have a tutorial that I made a couple of days ago. I've sent it to Kubilus already so I'm just waiting for his go-ahead before I can post it. 🤞

**Comment by kubilus1** [comment]
I'm really glad to see some success being replicated.   The guide looks really useful for get up and going in a Windows environment.  I still hope to streamline some more setup stuff, and to continue to look at solutions not involving WSL2 (if feasible).

As for the project itself, I'm identifying a few ways that the performance and memory efficiency can be improved.  I've noticed that disabling threaded mode for FUSE causes *much* better memory efficiency.  This doesn't seem right, so I'm tracking it down.  Stay tuned!

**Comment by SriharshaKavuri** [comment]
[AutomaticOrthoGeneratorInstallation.pdf](https://github.com/kubilus1/autoortho/files/9667551/AutomaticOrthoGeneratorInstallation.pdf)

@betampona hope this helps!

**Comment by betampona** [comment]
Hello, thank you for the tutorial it is of very good quality.
But I have a problem in chapter 6 of The instructions that follow will be usage related.
I typed the function \\\wsl$ \Ubuntu-22.04 \home I have an icon wsl$ on the left column where are all the disks and folders, it tells me that this folder is empty, I try to transfer ortho_in in this folder but it is impossible.
Greetings

**Comment by betampona** [comment]
I have found my previous error, I had to launch ubuntu to get the right window.
Now I have another problem I can't remove the # character from the last line of GNU nano 6.2
I highlight the # character of the last line then I do CTRL X then CTRL Y and ENTER nothing happens, I looked on the internet I didn't find anything conclusive ?
Greetings.

**Comment by SriharshaKavuri** [comment]
Ah, I should have outlined that better! To remove the character you have to use your delete/backspace keys. The sequence mentioned is to save the file after you remove the character.

**Comment by betampona** [comment]
You can send me the text content of GNU nano 6.2 because I have overwritten the lines and they are saved, now I have nothing.
I have to retype everything and save it.
Greetings

**Comment by betampona** [comment]
I'm moving slowly, I've finished the installation.
I'll send you a picture of authoortho, because I can't see the tiles on the ground
![Capture autoortho](https://user-images.githubusercontent.com/97102929/193419038-6532174c-2574-43e1-8ec3-193ed2556ee4.jpg)

**Comment by SriharshaKavuri** [comment]
Did you put the dsf files into ortho_in?

**Comment by betampona** [comment]
Hello, I have these lines in orange when I type: sudo python3 -m pip install -U -r requirements.tx
Could this interfere with the operation?
![Capture sudo python3](https://user-images.githubusercontent.com/97102929/193534806-b09adc96-9629-4f08-aa59-c4a47b618e02.jpg)

**Comment by SriharshaKavuri** [comment]
Nope! Shouldn't be an issue

**Comment by betampona** [comment]
![orto_in](https://user-images.githubusercontent.com/97102929/193566956-48f64f08-dfcb-40cd-a321-82132b9582e2.JPG)

here is the content of ortho_in it concerns the island of Dominica, there is only one tile.
When I run via ubuntu cd ~/autoortho and python3 autoortho, the content of ortho_in switches well to z_ortho and also fills the custom scenery of x-plane folder sc_ortho and the shortcut of z_ortho which is inside.
For me autoortho doesn't work, it doesn't recognize the launch of X-plane.
I have 2 disks on C: I have ubuntu and autoortho and x-plane 11 is on the G:
Greetings.

**Comment by SriharshaKavuri** [comment]
> sc_ortho and the shortcut of z_ortho which is inside

That would be the problem! The shortcut must be placed directly within the custom scenery folder.

**Comment by betampona** [comment]
When I put the z_ortho shortcut directly into the custom scenery it creates a number of errors, see the image and it blocks x-plane, I have to reboot the PC.
![Capture error getting](https://user-images.githubusercontent.com/97102929/193582461-b9c9551f-54fc-449f-ad9a-8d78cf9e22e4.jpg)

**Comment by SriharshaKavuri** [comment]
Google is not responding to your requests for some reason. This can happen and has happened on a few of my flights. There's no "fix" per se at the moment. Maybe @kubilus1 can implement something to skip a file if it returns too many errors.

**Comment by betampona** [comment]
Can we change with Bing? or can it do the same thing

**Comment by SriharshaKavuri** [comment]
Oh definitely! That's what I did too

**Comment by kubilus1** [comment]
Oh the issue is that 'GO2' is being interepreted as the 'GO' type at zoom level 217.  Which isn't going to work that well lol.

**Comment by betampona** [comment]
Hi SriharshaKavuri, as far as your tutorial is concerned you can add as a prerequisite the download of WinFSP and python with the links.
For the Orho4XP part you can add in Batch Build tiles, Draw water masks and Extract overlays.
In paragraph 6 it would be good to show this window and say that ubuntu is activated
In paragraph 7 you can remove the sc_ortho folder in custom scenery and say that the z_ortho shortcut is to be installed directly in custom scenery.
In paragraph 9, concerning the symbol # show exactly how to make it disappear, for the registration it is ok,
Thank you for the tutorial which allowed me to make autoortho operational.
Thanks for the tutorial which allowed me to make autoortho operational. Greetings.

**Comment by SriharshaKavuri** [comment]
Thanks for the feedback!

**Comment by SriharshaKavuri** [comment]
Woah that is gonna make it so much easier to install!

**Comment by betampona** [comment]
Good news, let's be patient.

**Comment by ekc007** [comment]
Hi, I have followed the installation instructions from SriharshaKavuri for Windows. Everything worked and it should be set up now. But when I try to copy the contents (according to Point 6 of "usage related inctructions") of my ortho4xp created tiles, the message shows up that several files already exist and if I want to override or skip them.
However I just tried to override and test it, but after a lot of messages in the Ubuntu window, X-Plane crashed.
I can post some screenshots if it helps, but there are too many different messages so at first I wanted to ask if I do something wrong with copying the contents maybe.
Many thanks for any help!

**Comment by SriharshaKavuri** [comment]
Heya! That overlap may happen in some areas. Overwriting would be the right course of action. It would be helpful if you could post some screenshots of the errors however.

**Comment by ekc007** [comment]
Hi, thanks for the quick reply. Here you will find some screenshots (the full list of messages is very long), although there are not many error messages. More warnings with "failed to get chunk", "no cache found"..
The last screenshot is the end of the list, after which X-Plane crashed.

![Unbenannt](https://user-images.githubusercontent.com/115185844/194551756-98e6ab6d-3693-433c-95fb-1f05a7b5969c.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/115185844/194551759-997da108-29b6-4511-8230-8a943bf8d985.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/115185844/194551762-4996a9b7-cd76-4c93-868e-90a2295b849e.PNG)
![Unbenannt4](https://user-images.githubusercontent.com/115185844/194551753-4714ed49-b028-43e2-85fe-8cc8c9922719.PNG)

**Comment by kubilus1** [comment]
Alright, I've cut a pre-release v0.0.5 that no longer should need WSL to run.  You'll need to install WinFSP, of course.

I've enabled the 'discussions' feature, which is probably a better place for general Windows usage that this thread has become, so I'll be moving over to that.
