### ISSUE TITLE
0.4.3 .exe CTD

### ISSUE THREAD

**Issue by rt23456p** [kubilus1/autoortho#167]
ERROR:fuse:FUSE operation read raised an OSError with an invalid errno None, returning errno.EINVAL.
Traceback (most recent call last):
  File "C:\Users\Leo\AppData\Local\Temp\ON9CE7~1\refuse\high.py", line 863, in _wrapper
  File "C:\Users\Leo\AppData\Local\Temp\ON9CE7~1\refuse\high.py", line 974, in read
  File "C:\Users\Leo\AppData\Local\Temp\ON9CE7~1\refuse\high.py", line 1222, in __call__
  File "C:\Users\Leo\AppData\Local\Temp\ON9CE7~1\autoortho_fuse.py", line 345, in read
  File "C:\Users\Leo\AppData\Local\Temp\ON9CE7~1\getortho.py", line 662, in read_dds_bytes
  File "C:\Users\Leo\AppData\Local\Temp\ON9CE7~1\getortho.py", line 80, in wrapped
  File "C:\Users\Leo\AppData\Local\Temp\ON9CE7~1\getortho.py", line 882, in get_mipmap
  File "C:\Users\Leo\AppData\Local\Temp\ON9CE7~1\getortho.py", line 80, in wrapped
  File "C:\Users\Leo\AppData\Local\Temp\ON9CE7~1\getortho.py", line 743, in get_img
  File "C:\Users\Leo\AppData\Local\Temp\ON9CE7~1\aoimage\AoImage.py", line 122, in new
OSError: exception: single step

Constant CTD and this is the only thing I can find on the console

**Comment by rt23456p** [comment]
https://drive.google.com/file/d/1FgidOLmJ5eTJuK5hEC5j7riTZIyxYUKX/view?usp=sharing 

Log File(214MB)
