### ISSUE TITLE
CTD with Single Step Error

### ISSUE THREAD

**Issue by rt23456p** [kubilus1/autoortho#173]
Log from Autoortho:

ERROR:fuse:FUSE operation read raised an OSError with an invalid errno None, returning errno.EINVAL.
Traceback (most recent call last):
  File "C:\Users\Leo\AppData\Local\Temp\ONB021~1\refuse\high.py", line 863, in _wrapper
  File "C:\Users\Leo\AppData\Local\Temp\ONB021~1\refuse\high.py", line 974, in read
  File "C:\Users\Leo\AppData\Local\Temp\ONB021~1\refuse\high.py", line 1222, in __call__
  File "C:\Users\Leo\AppData\Local\Temp\ONB021~1\autoortho_fuse.py", line 345, in read
  File "C:\Users\Leo\AppData\Local\Temp\ONB021~1\getortho.py", line 662, in read_dds_bytes
  File "C:\Users\Leo\AppData\Local\Temp\ONB021~1\getortho.py", line 80, in wrapped
  File "C:\Users\Leo\AppData\Local\Temp\ONB021~1\getortho.py", line 882, in get_mipmap
  File "C:\Users\Leo\AppData\Local\Temp\ONB021~1\getortho.py", line 80, in wrapped
  File "C:\Users\Leo\AppData\Local\Temp\ONB021~1\getortho.py", line 765, in get_img
  File "C:\Users\Leo\AppData\Local\Temp\ONB021~1\aoimage\AoImage.py", line 105, in paste
OSError: exception: single step

**Comment by rt23456p** [comment]
Faulting application name: autoortho_win.exe, version: 0.0.0.0, time stamp: 0x6444345a
Faulting module name: python310.dll, version: 3.10.11150.1013, time stamp: 0x642cc3cb
Exception code: 0x80000004
Fault offset: 0x0000000000071783
Faulting process id: 0x16b4
Faulting application start time: 0x01d9914faf2f5839
Faulting application path: C:\Users\Leo\AppData\Local\Temp\onefile_6368_133297435405787146\autoortho_win.exe
Faulting module path: C:\Users\Leo\AppData\Local\Temp\onefile_6368_133297435405787146\python310.dll
Report Id: 155a8b3f-34b0-4223-84e0-dccbd70ae382
Faulting package full name: 
Faulting package-relative application ID:
