### ISSUE TITLE
v0.6.0 Immediate shutdown after starting on Ubuntu Linux

### ISSUE THREAD

**Issue by h-a-l-t-e-r** [kubilus1/autoortho#347]
INFO:autoortho:Detected installed scenery:
INFO:autoortho:    /files/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_sa
INFO:autoortho:        Mounted? True
INFO:autoortho:    /files/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_aus_pac
INFO:autoortho:        Mounted? True
INFO:autoortho:    /files/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_eur
INFO:autoortho:        Mounted? True
INFO:autoortho:    /files/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_asi
INFO:autoortho:        Mounted? True
INFO:autoortho:    /files/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_na
INFO:autoortho:        Mounted? True
INFO:autoortho:    /files/X-Plane 12/Custom Scenery/z_autoortho/scenery/z_ao_afr
INFO:autoortho:        Mounted? True
INFO:autoortho:Shutting down ...
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_sa
Send poison pill ...
INFO:autoortho_fuse:Poison pill.  Exiting!
fuse_exit called
c_void_p(139952851920384)
fuse: fuse_remove_signal_handlers: unknown session
INFO:autoortho_fuse:FUSE: Exiting mount /files/X-Plane 12/Custom Scenery/z_ao_sa
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_sa
Send poison pill ...
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_aus_pac
Send poison pill ...
INFO:autoortho_fuse:Poison pill.  Exiting!
fuse_exit called
c_void_p(139952650200176)
fuse: fuse_remove_signal_handlers: unknown session
INFO:autoortho_fuse:FUSE: Exiting mount /files/X-Plane 12/Custom Scenery/z_ao_aus_pac
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_aus_pac
Send poison pill ...
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_eur
Send poison pill ...
INFO:autoortho_fuse:Poison pill.  Exiting!
fuse_exit called
c_void_p(139952515983568)
fuse: fuse_remove_signal_handlers: unknown session
INFO:autoortho_fuse:FUSE: Exiting mount /files/X-Plane 12/Custom Scenery/z_ao_eur
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_eur
Send poison pill ...
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_asi
Send poison pill ...
INFO:autoortho_fuse:Poison pill.  Exiting!
fuse_exit called
c_void_p(139952583091888)
fuse: fuse_remove_signal_handlers: unknown session
INFO:autoortho_fuse:FUSE: Exiting mount /files/X-Plane 12/Custom Scenery/z_ao_asi
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_asi
Send poison pill ...
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_na
Send poison pill ...
INFO:autoortho_fuse:Poison pill.  Exiting!
fuse_exit called
c_void_p(139952381764704)
fuse: fuse_remove_signal_handlers: unknown session
INFO:autoortho_fuse:FUSE: Exiting mount /files/X-Plane 12/Custom Scenery/z_ao_na
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_na
Send poison pill ...
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_afr
Send poison pill ...
INFO:autoortho_fuse:Poison pill.  Exiting!
fuse_exit called
c_void_p(139952448873472)
INFO:autoortho_fuse:FUSE: Exiting mount /files/X-Plane 12/Custom Scenery/z_ao_afr
Shutting down /files/X-Plane 12/Custom Scenery/z_ao_afr
Send poison pill ...
Thread 139953002497600 exited.
Thread 139952784406080 exited.
Thread 139952776013376 exited.
Thread 139952767620672 exited.
Thread 139952759227968 exited.
Thread 139952750835264 exited.
Traceback (most recent call last):
  File "/tmp/onefile_2040713_1693162154_223511/_pytest/config/__init__.py", line 782, in import_plugin
ModuleNotFoundError: No module named '_pytest.unittest'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/onefile_2040713_1693162154_223511/__main__.py", line 35, in <module>
  File "/tmp/onefile_2040713_1693162154_223511/autoortho.py", line 264, in main
  File "/tmp/onefile_2040713_1693162154_223511/autoortho.py", line 65, in diagnose
  File "/tmp/onefile_2040713_1693162154_223511/_pytest/config/__init__.py", line 147, in main
  File "/tmp/onefile_2040713_1693162154_223511/_pytest/config/__init__.py", line 319, in _prepareconfig
  File "/tmp/onefile_2040713_1693162154_223511/_pytest/config/__init__.py", line 289, in get_config
  File "/tmp/onefile_2040713_1693162154_223511/_pytest/config/__init__.py", line 784, in import_plugin
  File "/tmp/onefile_2040713_1693162154_223511/_pytest/config/__init__.py", line 782, in import_plugin
ImportError: Error importing plugin "unittest": No module named '_pytest.unittest'

**Comment by h-a-l-t-e-r** [comment]
The latest version is working OK.
