### ISSUE TITLE
Scenery install fail due to asterisk folder in /y_aus_pac/yOrtho4XP_Overlays/Earth nav data/

### ISSUE THREAD

**Issue by hawajka76** [kubilus1/autoortho#404]
I've just downloaded the lates version and started downloading scenery. Unfortunately I get the error below during installation. 
I'm on Linux and installing scenery on an NTFS drive. The issue is caused by one of the folders in the downloaded y_aus_pac_overlays.zip containing an empty folder which is named with an asterisk. 

Error traceback. 

ERROR:config_ui:Traceback (most recent call last):
  File "/tmp/onefile_11167_1696377872_979715/config_ui.py", line 320, in scenery_setup
  File "/tmp/onefile_11167_1696377872_979715/downloader.py", line 607, in install_release
  File "/tmp/onefile_11167_1696377872_979715/downloader.py", line 489, in install
  File "/tmp/onefile_11167_1696377872_979715/downloader.py", line 247, in install
  File "/tmp/onefile_11167_1696377872_979715/downloader.py", line 114, in extract
  File "/tmp/onefile_11167_1696377872_979715/zipfile.py", line 1647, in extractall
  File "/tmp/onefile_11167_1696377872_979715/zipfile.py", line 1697, in _extract_member
OSError: [Errno 22] Invalid argument: '/media/piotr/NVMe M.2/X-plane scenery/Custom Scenery/yAutoOrtho_Overlays/y_aus_pac/yOrtho4XP_Overlays/Earth nav data/*'

^CTraceback (most recent call last):
  File "/tmp/onefile_11167_1696377872_979715/__main__.py", line 35, in <module>
  File "/tmp/onefile_11167_1696377872_979715/autoortho.py", line 132, in main
  File "/tmp/onefile_11167_1696377872_979715/config_ui.py", line 69, in setup
  File "/tmp/onefile_11167_1696377872_979715/config_ui.py", line 285, in ui_loop
  File "/tmp/onefile_11167_1696377872_979715/PySimpleGUI/PySimpleGUI.py", line 19393, in popup
  File "/tmp/onefile_11167_1696377872_979715/PySimpleGUI/PySimpleGUI.py", line 10075, in read
  File "/tmp/onefile_11167_1696377872_979715/PySimpleGUI/PySimpleGUI.py", line 10146, in _read
  File "/tmp/onefile_11167_1696377872_979715/PySimpleGUI/PySimpleGUI.py", line 9886, in _Show
  File "/tmp/onefile_11167_1696377872_979715/PySimpleGUI/PySimpleGUI.py", line 16935, in StartupTK

**Comment by hawajka76** [comment]
It is just a simple fix, just need to remove the "*" folder from the zipped files which are being downloaded!

**Comment by hawajka76** [comment]
Just was curious if it is possible to get those zipped files updated? Please?
