### ISSUE TITLE
WinFSPyError: Cannot create file system: STATUS_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by evwltrs** [kubilus1/autoortho#44]
Using 0.3 RC2 and getting this error on windows:
`
Traceback (most recent call last):                                                                                        File "G:\Temp\onefile_1420_133206948425020505\autoortho.py", line 139, in <module>                                      File "G:\Temp\onefile_1420_133206948425020505\autoortho.py", line 86, in main                                           File "G:\Temp\onefile_1420_133206948425020505\autoortho_winfsp.py", line 471, in main                                   File "G:\Temp\onefile_1420_133206948425020505\autoortho_winfsp.py", line 444, in create_file_system                     File "G:\Temp\onefile_1420_133206948425020505\winfspy\file_system.py", line 116, in __init__                            File "G:\Temp\onefile_1420_133206948425020505\winfspy\file_system.py", line 156, in _create_file_system               winfspy.plumbing.exceptions.WinFSPyError: Cannot create file system: STATUS_INSUFFICIENT_RESOURCES
`

**Comment by evwltrs** [comment]
Fixed by installing [WinFSP 2022.2 Update1](https://github.com/winfsp/winfsp/releases/tag/v1.12.22339)

**Comment by kubilus1** [comment]
Good to know!
