### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by rudiratlos** [kubilus1/autoortho#453]
headless VM (no X-GUI) virtual debian machine (Linux ortho 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux)

I want to run a dedicated VM for autoortho. Downloaded scenery files  to (/nfs/Ortho4XP/.autoortho-data/downloads)
X-Plane (MacBook) will mount nfs share from this dedicated VM. 
How can I install the downloaded scenery files without the gui?

`root@ortho:~# /usr/local/sbin/autoortho_lin_0.7.1.bin -c -H
Config file found /root/.autoortho reading...
Found sceneries: []
[]
Saving config ... 
Wrote config file: /root/.autoortho
INFO:__main__:Setup logs: /root/.autoortho-data/logs, log level: 10
INFO:autoortho:AutoOrtho version: 0.7.1
INFO:aostats:Creating stats object
INFO:flighttrack:Start flighttracker...
INFO:aostats:Starting stats thread
WARNING:werkzeug:WebSocket transport not available. Install simple-websocket for improved performance.
 * Serving Flask app 'flighttrack'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.8.81.141:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:autoortho:Running CFG UI
Traceback (most recent call last):
  File "/tmp/onefile_13695_1699180650_938623/__main__.py", line 35, in <module>
  File "/tmp/onefile_13695_1699180650_938623/autoortho.py", line 355, in main
  File "/tmp/onefile_13695_1699180650_938623/autoortho.py", line 279, in __init__
  File "/tmp/onefile_13695_1699180650_938623/config_ui.py", line 43, in __init__
  File "/tmp/onefile_13695_1699180650_938623/config_ui.py", line 64, in start_splash
  File "/tmp/onefile_13695_1699180650_938623/PySimpleGUI/PySimpleGUI.py", line 9614, in __init__
  File "/tmp/onefile_13695_1699180650_938623/PySimpleGUI/PySimpleGUI.py", line 10300, in finalize
  File "/tmp/onefile_13695_1699180650_938623/PySimpleGUI/PySimpleGUI.py", line 10075, in read
  File "/tmp/onefile_13695_1699180650_938623/PySimpleGUI/PySimpleGUI.py", line 10146, in _read
  File "/tmp/onefile_13695_1699180650_938623/PySimpleGUI/PySimpleGUI.py", line 9886, in _Show
  File "/tmp/onefile_13695_1699180650_938623/PySimpleGUI/PySimpleGUI.py", line 16817, in StartupTK
  File "/tmp/onefile_13695_1699180650_938623/PySimpleGUI/PySimpleGUI.py", line 16704, in _get_hidden_master_root
  File "/tmp/onefile_13695_1699180650_938623/tkinter/__init__.py", line 2304, in __init__
_tkinter.TclError: no display name and no $DISPLAY environment variable`

**Comment by rudiratlos** [comment]
if I run it with -H, it clearly states that no scenery is installed

`root@ortho:/home/pi# /usr/local/sbin/autoortho_lin_0.7.1.bin -H
Config file found /root/.autoortho reading...
[]
Saving config ... 
Wrote config file: /root/.autoortho
INFO:__main__:Setup logs: /root/.autoortho-data/logs, log level: 10
INFO:autoortho:AutoOrtho version: 0.7.1
INFO:aostats:Creating stats object
INFO:flighttrack:Start flighttracker...
INFO:aostats:Starting stats thread
WARNING:werkzeug:WebSocket transport not available. Install simple-websocket for improved performance.
INFO:autoortho:Running headless
WARNING:autoortho:No installed sceneries detected.  Exiting.
INFO:aostats:Stopping stats thread
 * Serving Flask app 'flighttrack'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.8.81.141:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:aostats:STATS: ID: {}
INFO:flighttrack:FlightTracker shutdown requested.
INFO:flighttrack:FlightTracker exiting.
INFO:autoortho:AutoOrtho exit.
`

**Comment by rudiratlos** [comment]
How to force the installation of downloaded scenery files ?
