### ISSUE TITLE
Got error ERROR:winfspy:Unhandled exception

### ISSUE THREAD

**Issue by alizdavoodi** [kubilus1/autoortho#50]
Hey,

Thanks a lot for this excellent utility.
I'm on windows 11, and I wanted to use autoortho on xp12.

But I got this error, although I saw the tiles in the cache folder when I started the xp12. It takes 45 min to retrieve the tiles.
I already installed winfs version winfsp-1.12.22339

```
ERROR:winfspy:Unhandled exception
Traceback (most recent call last):
  File "C:\Users\Alireza\AppData\Local\Temp\ON5332~1\winfspy\operations.py", line 20, in wrapper
  File "C:\Users\Alireza\AppData\Local\Temp\ON5332~1\winfspy\operations.py", line 433, in ll_set_basic_info
  File "C:\Users\Alireza\AppData\Local\Temp\ON5332~1\winfspy\operations.py", line 468, in set_basic_info
NotImplementedError
INFO:flighttrack:FT: Flight is starting.
INFO:flighttrack:FT: Time to start was 42.85 minutes
```
I've uploaded the whole log file in case :)
[autoortho.log](https://github.com/kubilus1/autoortho/files/10774015/autoortho.log)

**Comment by ivotaHR** [comment]
Try delete  link folder (textures) in 
X:\X-Plane 12\Custom Scenery\z_autoortho\textures

**Comment by alizdavoodi** [comment]
Update:

When I try to open the textures folder, this error occurred:

```
ERROR:winfspy:Unhandled exception
Traceback (most recent call last):
  File "C:\Users\Alireza\AppData\Local\Temp\ONEFIL~2\winfspy\operations.py", line 20, in wrapper
  File "C:\Users\Alireza\AppData\Local\Temp\ONEFIL~2\winfspy\operations.py", line 601, in ll_read_directory
TypeError: AutoorthoOperations.read_directory() missing 1 required positional argument: 'buffer_len'
```
