### ISSUE TITLE
Error while trying to install scenary package

### ISSUE THREAD

**Issue by Sebastiano1412** [kubilus1/autoortho#537]
**Describe the bug**
During the installation of one of the scenary package (africa and america both gave this error), the installation blocks after a few minutes giving this error:
ERROR:config_ui:Traceback (most recent call last):
  File "C:\Users\sebas\AppData\Local\Programs\AUTOOR~1\config_ui.py", line 376, in scenery_setup
  File "C:\Users\sebas\AppData\Local\Programs\AUTOOR~1\downloader.py", line 604, in install_release
  File "C:\Users\sebas\AppData\Local\Programs\AUTOOR~1\downloader.py", line 460, in download
  File "C:\Users\sebas\AppData\Local\Programs\AUTOOR~1\downloader.py", line 197, in download
  File "C:\Users\sebas\AppData\Local\Programs\AUTOOR~1\urllib\request.py", line 280, in urlretrieve
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 440401920 out of 1073741824 bytes>.

I have tried using only dokan and both dokan and winfsp. I have tried disabling the firewall in windows, without improving anything.

**To Reproduce**
Start the download of any scenary package and wait for some minutes

**(please complete the following information):**
 - OS: Windows 11
 - XPlane Version: XP12 Beta 12.1.2b2
 - AutoOrtho Version: 0.7.2

**Additional context**
Logs attached
[autoortho.log](https://github.com/user-attachments/files/16801118/autoortho.log)

**Comment by jehad1990** [comment]
I can confirm I am getting same issue for Asia

**Comment by snrjuanfran** [comment]
Same issue here, hope the dev addresses it. Seems to be a server issue.
