### ISSUE TITLE
SSL cert expired for eur_02.zip

### ISSUE THREAD

**Issue by bonkzwonil** [kubilus1/autoortho#84]
when downloading eur_02.zip it runs into an expired ssl certificate which dumps a stack trace.

After this the program can not be restarted:

```
Traceback (most recent call last):
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 1348, in do_open
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\http\client.py", line 1282, in request
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\http\client.py", line 1328, in _send_request
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\http\client.py", line 1277, in endheaders
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\http\client.py", line 1037, in _send_output
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\http\client.py", line 975, in send
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\http\client.py", line 1454, in connect
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\ssl.py", line 513, in wrap_socket
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\ssl.py", line 1071, in _create
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\ssl.py", line 1342, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\__main__.py", line 26, in <module>
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\autoortho.py", line 52, in main
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\aoconfig.py", line 87, in setup
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\aoconfig.py", line 145, in ui_loop
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\downloader.py", line 474, in find_releases
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\downloader.py", line 74, in __init__
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\downloader.py", line 100, in get_rel_info
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\downloader.py", line 25, in do_url
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 216, in urlopen
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 525, in open
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 634, in http_response
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 557, in error
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 496, in _call_chain
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 749, in http_error_302
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 519, in open
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 536, in _open
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 496, in _call_chain
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 1391, in https_open
  File "C:\Users\bonk\AppData\Local\Temp\ONEFIL~3\urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>


```

**Comment by ivotaHR** [comment]
today. Same problem

**Comment by ivotaHR** [comment]
INFO:downloader:Looking for regions ...
INFO:downloader:Last release refresh time: 2023-03-24 21:48:57.565253
INFO:downloader:Using cache ...
INFO:downloader:Using scenery dir C:/X-Plane 12/Custom Scenery
INFO:downloader:Found region sa version 0.0.46-1
Traceback (most recent call last):
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 1348, in do_open
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\http\client.py", line 1282, in request
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\http\client.py", line 1328, in _send_request
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\http\client.py", line 1277, in endheaders
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\http\client.py", line 1037, in _send_output
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\http\client.py", line 975, in send
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\http\client.py", line 1454, in connect
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\ssl.py", line 513, in wrap_socket
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\ssl.py", line 1071, in _create
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\ssl.py", line 1342, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\__main__.py", line 26, in <module>
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\autoortho.py", line 52, in main
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\aoconfig.py", line 87, in setup
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\aoconfig.py", line 145, in ui_loop
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\downloader.py", line 474, in find_releases
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\downloader.py", line 74, in __init__
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\downloader.py", line 100, in get_rel_info
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\downloader.py", line 25, in do_url
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 216, in urlopen
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 525, in open
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 634, in http_response
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 557, in error
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 496, in _call_chain
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 749, in http_error_302
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 519, in open
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 536, in _open
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 496, in _call_chain
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 1391, in https_open
  File "C:\Users\Ivica\AppData\Local\Temp\ONEFIL~4\urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

**Comment by bonkzwonil** [comment]
seems also to applz to all regions now. 
The cert for everything just seemed to have expired :(

**Comment by ivotaHR** [comment]
session.get("https://python.org", ssl=False)

**Comment by ivotaHR** [comment]
now ALL ok. I renew my WAN IP.

**Comment by bonkzwonil** [comment]
exporting `PYTHONHTTPSVERIFY=0` lets one obviously bypass it (not recommended. though)

**Comment by kubilus1** [comment]
External issue.  Github certs was expired, not much I can do about that, but looks like it's sorted on their end now.

**Comment by bonkzwonil** [comment]
yes I can confirm. Works now again. thanks
